export {
  createPatternAlgorithm,
  type PatternAlgorithm,
  type PatternAlgorithmConfig,
} from './algorithm.js'
export {
  colorDistance,
  deltaE76,
  deltaE2000,
  rgbToLab,
} from './color.js'
export { optimizeGrid } from './grid.js'
export { adaptPattern } from './adaptation.js'
export { composeCandidateEvaluationV2 } from './candidate-evaluation.js'
export {
  applyArtDirectionImportance,
  enforceTileSeams,
  planPixelArtDirection,
  selectAnimationKeyFrame,
} from './art-direction.js'
export type {
  AnimationFrameCandidate,
  AnimationKeyFrameSelection,
  ArtDirectionExecutionSummary,
  ArtDirectionImportanceInput,
  ArtDirectionImportanceResult,
  ArtDirectionImportanceSummary,
  MaterialDirectionProfile,
  PixelArtDirectionInput,
  PixelArtDirectionPlan,
  PixelArtMode,
  SceneLayerId,
  TileSeamInput,
  TileSeamResult,
  TileSeamSummary,
  TextureDirection,
} from './art-direction.js'
export { fitBradleyTerry, predictPairwisePreference } from './preference.js'
export type {
  BradleyTerryOptions,
  BradleyTerryResult,
  CandidatePreferenceScore,
  PairwisePreferenceChoice,
  PairwisePreferenceRecord,
} from './preference.js'
export {
  BASELINE_PREFERENCE_WEIGHTS,
  PREFERENCE_AXES,
  PREFERENCE_FEATURES,
  PREFERENCE_ISSUES,
  PREFERENCE_RECORD_SCHEMA_VERSION,
  comparePreferenceModels,
  createFrozenPreferenceSplit,
  deduplicatePreferenceRecords,
  derivePreferenceGenerationParameters,
  fitPreferenceModelV2,
  migratePairwisePreferenceRecord,
  normalizePreferenceRecordV2,
  preferenceRecordFromWorkbenchSession,
  preferenceRecordFingerprint,
  rankPreferenceCandidates,
  replayPreferenceRecord,
  selectActivePreferencePair,
  selectPreferenceModelVersion,
  validatePreferenceRecordV2,
} from './preference-v2.js'
export type {
  ActivePreferencePairOptions,
  ActivePreferencePair,
  ComparedPreferencePair,
  FrozenPreferenceSplit,
  FrozenPreferenceSplitOptions,
  PreferenceAxis,
  PreferenceAxisScores,
  PreferenceAnnotatorIdentity,
  PreferenceCandidateRankScore,
  PreferenceCandidateRoute,
  PreferenceCandidateV2,
  PreferenceCellSelection,
  PreferenceCompositeChoice,
  PreferenceComparisonV2,
  PreferenceElimination,
  PreferenceEvaluationMetrics,
  PreferenceFeatureName,
  PreferenceFeatureVector,
  PreferenceGenerationAdjustments,
  PreferenceGenerationParameters,
  PreferenceIssue,
  PreferenceIssueAnnotation,
  PreferenceModelComparison,
  PreferenceModelContext,
  PreferenceModelIdentity,
  PreferenceModelOptions,
  PreferenceModelSelection,
  PreferenceModelSelectionOptions,
  PreferenceModelV2,
  PreferenceRankingResult,
  PreferenceRecordV2,
  PreferenceRegionSelection,
  PreferenceReplayResult,
  PreferenceSourceIdentity,
  PreferenceStratumModel,
  PreferenceSubjectKind,
  PreferenceV1MigrationContext,
  PreferenceWorkbenchConversionOptions,
} from './preference-v2.js'
export {
  normalizeEvidenceProvenance,
  numericArrayFingerprintSync,
  resolvedSubjectMask,
  subjectMaskConfidence,
  subjectMaskTrust,
} from './analysis-evidence.js'
export {
  activeMaskStrokes,
  appendMaskEditStroke,
  applyMaskStroke,
  applyMaskStrokes,
  confirmMaskCorrection,
  confirmMaskEditSession,
  createMaskCorrectionDraft,
  createMaskCorrectionDraftFromSession,
  createMaskEditSession,
  redoMaskEdit,
  undoMaskEdit,
} from './mask-correction.js'
export type {
  MaskCorrectionDraft,
  MaskEditSession,
  MaskPoint,
  MaskStroke,
  MaskStrokeMode,
} from './mask-correction.js'
export type {
  AlgorithmEngine,
  ArtDirectionOptions,
  BaselineMode,
  BeadPattern,
  BinaryMask,
  CandidateEvaluation,
  CandidateEvaluationModelIdentity,
  CandidateEvaluationScoreV2,
  CandidateEvaluationSourceWeights,
  CandidateEvaluationV2,
  CandidateEvaluationV2Input,
  CandidateNeuralPreferenceFeatures,
  CandidateProviderContribution,
  CandidateScore,
  CanvasOptions,
  ColorDistanceMethod,
  CropRect,
  EvidenceOrigin,
  EvidenceProvenance,
  GenerationMetrics,
  GenerationStatus,
  GenerationTiming,
  GridBudgetViolations,
  GridEditRecord,
  GridRefinementBudgets,
  GridRefinementMode,
  GridClusterDiagnostics,
  GridRefinementSummary,
  GridSize,
  ImageAnalysis,
  ImageLandmark,
  ImageType,
  ImportanceMap,
  Lab,
  LandmarkKind,
  LandmarkPriority,
  MaterialColor,
  MaterialCount,
  MaterialInventory,
  MaterialPalette,
  MaterialSubstitutionMap,
  OptimizationOptions,
  StructureOptions,
  PatternCandidate,
  PatternCell,
  PatternGenerationRequest,
  PatternGenerationResult,
  PatternGenerationSuccess,
  PatternGenerationBestEffort,
  PatternGenerationNoValidCandidate,
  PatternAdaptationRequest,
  PatternAdaptationResult,
  PatternAdaptationChange,
  MaterialDelta,
  PatternMetadata,
  PatternOptions,
  PatternStyle,
  PixelImage,
  SelectedPreferenceRankingInput,
  ResizeMethod,
  RGB,
  SemanticRegion,
  SubjectMaskEvidence,
  SubjectMaskSource,
} from './types.js'
export type {
  MaterialValueKind,
  SemanticGapDiagnostic,
  SemanticValueGaps,
  ValueGroupDiagnostic,
  ValueLighting,
  ValuePlanningDiagnostics,
} from './planning/value-planner.js'
export type {
  PalettePlanningDiagnostics,
  PaletteSubstitutionDiagnostic,
} from './planning/palette-planner.js'
