export {
  createPatternAlgorithm,
  type PatternAlgorithm,
  type PatternAlgorithmConfig,
} from './algorithm.js'
export {
  colorDistance,
  deltaE76,
  deltaE2000,
  rgbToLab,
} from './color.js'
export { optimizeGrid } from './grid.js'
export { adaptPattern } from './adaptation.js'
export {
  normalizeEvidenceProvenance,
  numericArrayFingerprintSync,
  resolvedSubjectMask,
  subjectMaskConfidence,
  subjectMaskTrust,
} from './analysis-evidence.js'
export {
  activeMaskStrokes,
  appendMaskEditStroke,
  applyMaskStroke,
  applyMaskStrokes,
  confirmMaskCorrection,
  confirmMaskEditSession,
  createMaskCorrectionDraft,
  createMaskCorrectionDraftFromSession,
  createMaskEditSession,
  redoMaskEdit,
  undoMaskEdit,
} from './mask-correction.js'
export type {
  MaskCorrectionDraft,
  MaskEditSession,
  MaskPoint,
  MaskStroke,
  MaskStrokeMode,
} from './mask-correction.js'
export type {
  AlgorithmEngine,
  BaselineMode,
  BeadPattern,
  BinaryMask,
  CandidateEvaluation,
  CandidateScore,
  CanvasOptions,
  ColorDistanceMethod,
  CropRect,
  EvidenceOrigin,
  EvidenceProvenance,
  GenerationMetrics,
  GenerationStatus,
  GenerationTiming,
  GridEditRecord,
  GridRefinementMode,
  GridRefinementSummary,
  GridSize,
  ImageAnalysis,
  ImageLandmark,
  ImageType,
  ImportanceMap,
  Lab,
  LandmarkKind,
  LandmarkPriority,
  MaterialColor,
  MaterialCount,
  MaterialPalette,
  OptimizationOptions,
  StructureOptions,
  PatternCandidate,
  PatternCell,
  PatternGenerationRequest,
  PatternGenerationResult,
  PatternGenerationSuccess,
  PatternGenerationBestEffort,
  PatternGenerationNoValidCandidate,
  PatternAdaptationRequest,
  PatternAdaptationResult,
  PatternAdaptationChange,
  MaterialDelta,
  PatternMetadata,
  PatternOptions,
  PatternStyle,
  PixelImage,
  ResizeMethod,
  RGB,
  SemanticRegion,
  SubjectMaskEvidence,
  SubjectMaskSource,
} from './types.js'
