import { expect, test } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'
test('switches MARD, Perler and generic catalogs and exports physical codes', async ({ page }) => {
  test.setTimeout(90_000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/apps/demo/')
  await expect(page.locator('#generateButton')).toBeEnabled({ timeout: 30_000 })
  // The synthetic neural eye masks can fail the quality gate on this real photo.
  // Exercise catalog/export behavior through the actual deterministic route.
  await page.locator('#sizeControl [data-size="32"]').click()
  await page.locator('#refinementModeControl [data-refinement="fast"]').click()
  for (const checkbox of await page.locator('#styleControl input:not([value="faithful"])').all()) await checkbox.uncheck()
  await page.selectOption('#modelRouteSelect', 'deterministic')
  await expect(page.locator('#downloadButton')).toBeEnabled({ timeout: 30_000 })
  await expect(page.locator('#paletteSelect')).toHaveValue('mard-291')
  await expect(page.locator('#maxColors')).toHaveAttribute('max', '48')
  await expect(page.locator('#materialList')).toContainText(/[A-Z]+\d+/)
  await page.selectOption('#exportFormat', 'json')
  const downloaded = page.waitForEvent('download')
  await page.click('#downloadButton')
  const doc = JSON.parse(await readFile(await (await downloaded).path(), 'utf8'))
  expect(doc.paletteId).toBe('mard-291')
  expect(doc.paletteVersion).toMatch(/^sha256:/)
  expect(doc.materials.reduce((n, m) => n + m.count, 0)).toBe(doc.grid.filter(i => i >= 0).length)
  await page.selectOption('#exportFormat', 'png')
  const png = page.waitForEvent('download')
  await page.click('#downloadButton')
  const pngBytes = await readFile(await (await png).path())
  expect(pngBytes.subarray(1, 4).toString()).toBe('PNG')
  await writeFile('output/mard-291-pattern.png', pngBytes)
  await page.screenshot({ path: 'output/demo-mard-291.png', fullPage: true })
  await page.selectOption('#paletteSelect', 'perler-123')
  await expect(page.locator('#paletteCount')).toHaveText('123 色')
  await expect(page.locator('#paletteNote')).toContainText('118 色')
  await expect(page.locator('#maxColors')).toHaveAttribute('max', '48')
  await expect(page.locator('#downloadButton')).toBeEnabled({ timeout: 45_000 })
  await page.selectOption('#exportFormat', 'json')
  const perlerDownload = page.waitForEvent('download')
  await page.click('#downloadButton')
  const perler = JSON.parse(await readFile(await (await perlerDownload).path(), 'utf8'))
  expect(perler.paletteId).toBe('perler-123')
  expect(perler.brand).toBe('Perler')
  expect(perler.colors.every(c => c.automaticMatch && c.finish === 'solid')).toBe(true)
  expect(perler.materials.every(m => /^(80-\d{5}|PER\d{5})$/.test(m.code))).toBe(true)
  expect(perler.materials.reduce((n, m) => n + m.count, 0)).toBe(perler.grid.filter(i => i >= 0).length)
  await page.selectOption('#exportFormat', 'csv')
  const csv = page.waitForEvent('download')
  await page.click('#downloadButton')
  const csvText = await readFile(await (await csv).path(), 'utf8')
  for (const material of perler.materials) expect(csvText).toContain(`"${material.code}"`)
  await page.selectOption('#exportFormat', 'png')
  const perlerPng = page.waitForEvent('download')
  await page.click('#downloadButton')
  const perlerPngBytes = await readFile(await (await perlerPng).path())
  expect(perlerPngBytes.subarray(1, 4).toString()).toBe('PNG')
  await writeFile('output/perler-123-pattern.png', perlerPngBytes)
  await page.screenshot({ path: 'output/demo-perler-123.png', fullPage: true })
  await page.selectOption('#paletteSelect', 'generic-24')
  await expect(page.locator('#paletteCount')).toHaveText('24 色')
  await expect(page.locator('#paletteNote')).toBeHidden()
  await expect(page.locator('#maxColors')).toHaveAttribute('max', '24')
  await expect(page.locator('#downloadButton')).toBeEnabled({ timeout: 30_000 })
  await page.selectOption('#exportFormat', 'json')
  const genericDownload = page.waitForEvent('download')
  await page.click('#downloadButton')
  expect(JSON.parse(await readFile(await (await genericDownload).path(), 'utf8')).paletteId).toBe('generic-24')
  expect(errors).toEqual([])
})
