import { expect, test } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'
test('uses the full MARD catalog, exports physical codes, and switches palettes', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/apps/demo/')
  await expect(page.locator('#downloadButton')).toBeEnabled({ timeout: 30_000 })
  await expect(page.locator('#paletteSelect')).toHaveValue('mard-291')
  await expect(page.locator('#maxColors')).toHaveAttribute('max', '48')
  await expect(page.locator('#materialList')).toContainText(/[A-Z]+\d+/)
  await page.selectOption('#exportFormat', 'json')
  const downloaded = page.waitForEvent('download')
  await page.click('#downloadButton')
  const doc = JSON.parse(await readFile(await (await downloaded).path(), 'utf8'))
  expect(doc.paletteId).toBe('mard-291')
  expect(doc.paletteVersion).toMatch(/^sha256:/)
  expect(doc.materials.reduce((n, m) => n + m.count, 0)).toBe(doc.grid.filter(i => i >= 0).length)
  await page.selectOption('#exportFormat', 'png')
  const png = page.waitForEvent('download')
  await page.click('#downloadButton')
  const pngBytes = await readFile(await (await png).path())
  expect(pngBytes.subarray(1, 4).toString()).toBe('PNG')
  await writeFile('output/mard-291-pattern.png', pngBytes)
  await page.screenshot({ path: 'output/demo-mard-291.png', fullPage: true })
  await page.selectOption('#paletteSelect', 'generic-24')
  await expect(page.locator('#paletteCount')).toHaveText('24 色')
  await expect(page.locator('#maxColors')).toHaveAttribute('max', '24')
  await expect(page.locator('#downloadButton')).toBeEnabled({ timeout: 30_000 })
  await page.selectOption('#exportFormat', 'json')
  const genericDownload = page.waitForEvent('download')
  await page.click('#downloadButton')
  expect(JSON.parse(await readFile(await (await genericDownload).path(), 'utf8')).paletteId).toBe('generic-24')
})
