import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { describe, it } from 'node:test'

describe('workbench product controls', () => {
  it('exposes grid refinement, planning diagnostics, and daily preference capture', async () => {
    const html = await readFile(new URL('./index.html', import.meta.url), 'utf8')

    assert.match(html, /id="refinementModeControl"/)
    assert.match(html, /id="gridRefinementEnergy"/)
    assert.match(html, /id="structureRegionCount"/)
    assert.match(html, /id="valueRoleCount"/)
    assert.match(html, /id="paletteRoleCount"/)
    assert.match(html, /id="clusterFragmentChange"/)
    assert.match(html, /id="smallComponentChange"/)
    assert.match(html, /id="singleCellBandChange"/)
    assert.match(html, /elements\.structureRegionCount\.textContent = candidate\.structurePlan === undefined/)
    assert.match(html, /id="preferencePanel"/)
    assert.match(html, /id="preferenceWorkbenchDialog"/)
    assert.match(html, /id="preferenceCandidateGrid"/)
    assert.match(html, /id="preferenceLayerControl"/)
    assert.match(html, /data-preference-layer="features"/)
    assert.match(html, /data-preference-layer="structure"/)
    assert.match(html, /data-preference-layer="value"/)
    assert.match(html, /data-preference-layer="refinement"/)
    assert.match(html, /id="preferenceAxisScores"/)
    assert.match(html, /id="preferenceIssueTags"/)
    assert.match(html, /id="preferenceUndoButton"/)
    assert.match(html, /id="preferenceRedoButton"/)
    assert.match(html, /id="preferenceProgress"/)
    assert.match(html, /id="preferenceExportJsonButton"/)
    assert.match(html, /id="preferenceExportJsonlButton"/)
    assert.match(html, /id="preferenceLearningPanel"/)
    assert.match(html, /id="preferenceLearningSampleCount"/)
    assert.match(html, /id="preferenceHoldoutComparison"/)
    assert.match(html, /id="preferenceRankingDifference"/)
    assert.match(html, /id="preferenceActivePair"/)
    assert.match(html, /id="preferenceGenerationFeedback"/)
    assert.match(html, /preferenceRuntime\.applyGenerationOptions/)
    assert.match(html, /preference-workbench-ui\.mjs/)
    assert.match(html, /preference-runtime\.mjs/)
    assert.match(html, /id="modelRouteSelect"/)
    assert.match(html, /id="modelRouteStatus"/)
    assert.match(html, /selectLearnedProposal/)
    assert.match(html, /学习像素化/)
    assert.match(html, /ai-runtime\.mjs/)
    assert.match(html, /data-analysis-layer="edges"/)
    assert.match(html, /data-analysis-layer="depth"/)
    assert.match(html, /data-analysis-layer="embedding"/)
    assert.match(html, /id="analysisDebugProvider"/)
    assert.match(html, /id="analysisDebugContributions"/)
  })

  it('fits rectangular uploads into square previews with their aspect ratio intact', async () => {
    const html = await readFile(new URL('./index.html', import.meta.url), 'utf8')

    assert.match(html, /Math\.min\(canvas\.width \/ buffer\.width, canvas\.height \/ buffer\.height\)/)
    assert.match(html, /\(canvas\.width - width\) \/ 2/)
    assert.match(html, /\(canvas\.height - height\) \/ 2/)
  })
})
