import { expect, test } from '@playwright/test'

test('keeps independent contour controls and manual sloping eye anchors through the demo', async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/apps/demo/')
  await expect(page.locator('#generateButton')).toBeEnabled({ timeout: 30_000 })
  await expect(page.locator('#externalContour')).toBeChecked()
  await expect(page.locator('#internalContour')).toBeChecked()
  await page.uncheck('#internalContour')
  await page.locator('#featureEditor summary').click()
  const editor = page.locator('#featureEditor')
  await editor.locator('[data-field="existing"]').focus()
  const ids = await editor.locator('[data-field="existing"] option').evaluateAll(nodes => nodes.map(n => n.value).filter(id => id.includes('eye')))
  expect(ids.length).toBeGreaterThanOrEqual(2)
  await editor.locator('[data-field="existing"]').selectOption(ids[0])
  const initialY = Number(await editor.locator('[data-field="y"]').inputValue())
  await editor.locator('[data-field="y"]').fill(String(initialY + 2))
  await editor.locator('[data-field="template"]').selectOption('eye-open-2x3')
  await editor.locator('[data-action="save"]').click()
  await expect(editor.locator('[data-field="status"]')).toContainText('已保存 1 个')
  await editor.locator('[data-field="existing"]').selectOption(ids[1])
  await editor.locator('[data-field="hidden"]').check()
  await editor.locator('[data-action="save"]').click()
  await expect(editor.locator('[data-field="status"]')).toContainText('已保存 2 个')
  await page.locator('[data-size="32"]').click()
  await page.locator('[data-occupancy="full-frame"]').click()
  await page.click('#generateButton')
  await expect(page.locator('#generateButton')).toBeEnabled({ timeout: 30_000 })
  await expect(page.locator('#featureStatus')).toContainText('eye-open-2x3')
  await expect(page.locator('#featureStatus')).not.toContainText(ids[1])
  await expect(page.locator('#externalContour')).toBeChecked()
  await expect(page.locator('#internalContour')).not.toBeChecked()
  await expect(page.locator('#contourStatus')).toContainText('轮廓')
  // The synthetic part fixture is incomplete: successful inference must not bypass quality gates.
  await expect(page.locator('#statusText')).toContainText('关键特征表达不足')
  await expect(page.locator('#downloadButton')).toBeDisabled()
  expect(errors).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('contours-features-demo.png'), fullPage: true })
})
